const JobsData = [
  {
    level: 'Fresher',
    company: 'Talentmate',
    img: 'https://image.talentmate.vn//400x0/prod/common/338964f8-1fdd-4f9f-ba6f-6247ba0fcea7-logo-talentmatepng.webp',
    alt: 'talentmate logo',
    position: 'Digital Marketing - Media Buyer',
    salary: '5.000',
    location: 'Da nang',
    exp: 'Over 10y exp',
    due: '16 october, 2023',
  },
  {
    level: 'Fresher',
    company: 'Nestle',
    img: 'https://1000logos.net/wp-content/uploads/2017/03/Nestle-Logo.png',
    alt: 'nestle logo',
    position: 'Digital Marketing - Media Buyer',
    salary: '5.000',
    location: 'Da nang',
    exp: 'Over 10y exp',
    due: '16 october, 2023',
  },

  {
    level: 'Junior',
    company: 'Highlands',
    img: 'https://cdn.haitrieu.com/wp-content/uploads/2022/03/highlands-coffee-red-logo.png',
    alt: 'highlands logo',
    position: 'Digital Marketing - Media Buyer',
    salary: '5.000',
    location: 'Da nang',
    exp: 'Over 10y exp',
    due: '16 october, 2023',
  },
  {
    level: 'Intermediate',
    company: 'FPT Software',
    img: 'https://hcmfpt.vn/vnt_upload/about/FPT_Telecom_logo.svg',
    alt: 'fpt software logo',
    position: 'Digital Marketing - Media Buyer',
    salary: '5.000',
    location: 'Da nang',
    exp: 'Over 10y exp',
    due: '16 october, 2023',
  },
  {
    level: 'Intermediate',
    company: 'Popeyes',
    img: 'https://1000logos.net/wp-content/uploads/2021/04/Popeyes-logo.png',
    alt: 'popeyes logo',
    position: 'Digital Marketing - Media Buyer',
    salary: '5.000',
    location: 'Da nang',
    exp: 'Over 10y exp',
    due: '16 october, 2023',
  },
  {
    level: 'Intermediate',
    company: 'Fox Wear',
    img: 'https://foxwears.vn/wp-content/uploads/2021/12/Untitled-2-e1611719094586.png',
    alt: 'fox wear logo',
    position: 'Digital Marketing - Media Buyer',
    salary: '5.000',
    location: 'Da nang',
    exp: 'Over 10y exp',
    due: '16 october, 2023',
  },
  {
    level: 'Lead',
    company: 'Orient Software',
    img: 'https://images02.vietnamworks.com//companyprofile/Orient-Software-Development/en/Orient_logo_V1_red_FINAL-01.png',
    alt: 'orient software logo',
    position: 'Digital Marketing - Media Buyer',
    salary: '5.000',
    location: 'Da nang',
    exp: 'Over 10y exp',
    due: '16 october, 2023',
  },
  {
    level: 'Manager',
    company: 'Sacombank',
    img: 'https://www.thuvienvector.com/upload/images/items/vector-logo-ngan-hang-sacombank-file-cdr-coreldraw-129.webp',
    alt: 'sacombank logo',
    position: 'Digital Marketing - Media Buyer',
    salary: '5.000',
    location: 'Da nang',
    exp: 'Over 10y exp',
    due: '16 october, 2023',
  },
  {
    level: 'Fresher',
    company: 'Misa',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Logo_MISA_JSC_Vie.jpg/1200px-Logo_MISA_JSC_Vie.jpg',
    alt: 'misa logo',
    position: 'Digital Marketing - Media Buyer',
    salary: '5.000',
    location: 'Da nang',
    exp: 'Over 10y exp',
    due: '16 october, 2023',
  },
  {
    level: 'Fresher',
    company: 'Obox',
    img: 'https://oboxdesigns.com/static/media/Logo_plus.10ed9600.svg',
    alt: 'obox logo',
    position: 'Digital Marketing - Media Buyer',
    salary: '5.000',
    location: 'Da nang',
    exp: 'Over 10y exp',
    due: '16 october, 2023',
  },
  {
    level: 'Fresher',
    company: 'VTC Intecom',
    img: 'https://haymora.com/upload/images/cong_nghe_thong_tin/top_50/vtc_intecom/logo-cong-ty-vtc-cong-nghe-va-noi-dung-so.jpg',
    alt: 'vtc intecom logo',
    position: 'Digital Marketing - Media Buyer',
    salary: '5.000',
    location: 'Da nang',
    exp: 'Over 10y exp',
    due: '16 october, 2023',
  },
  {
    level: 'Fresher',
    company: 'CMC T&S',
    img: 'https://cdn.cmc.com.vn/img/posts/Logo%20CMC%20CORP.jpg',
    alt: 'cmc t&s logo',
    position: 'Digital Marketing - Media Buyer',
    salary: '5.000',
    location: 'Da nang',
    exp: 'Over 10y exp',
    due: '16 october, 2023',
  },
  {
    level: 'Fresher',
    company: 'Code Gym',
    img: 'https://haymora.com/upload/images/cong_nghe_thong_tin/2020/codegym/codegym-logo.jpg',
    alt: 'code gym logo',
    position: 'Digital Marketing - Media Buyer',
    salary: '5.000',
    location: 'Da nang',
    exp: 'Over 10y exp',
    due: '16 october, 2023',
  },
  {
    level: 'Fresher',
    company: 'F8',
    img: 'https://yp.vn/wp-content/uploads/2022/04/f8-icon.7ad2b161d5e80c87e516.png',
    alt: 'f8 logo',
    position: 'Digital Marketing - Media Buyer',
    salary: '5.000',
    location: 'Da nang',
    exp: 'Over 10y exp',
    due: '16 october, 2023',
  },
];

export default JobsData;